{
  "compatibilityLevel": 1550,
  "model": {
    "annotations": [
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "0"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.131.1203.0 (24.07)"
      },
      {
        "name": "PBI_QueryOrder",
        "value": "[\"uc?export=download&id=1dPCDeD6N8GAZnzQ3QbfP7T_jYD1jYh0G\"]"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {
          "content": {
            "Language": "en-US",
            "Version": "1.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "uc?export=download&id=1dPCDeD6N8GAZnzQ3QbfP7T_jYD1jYh0G",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "Account ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2733549b-ad37-487c-a37e-904d0ee2ea5e",
            "sourceColumn": "Account ID",
            "summarizeBy": "none"
          },
          {
            "name": "Account Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6ee7a616-3d1b-4979-a3ed-338246c4e419",
            "sourceColumn": "Account Name",
            "summarizeBy": "none"
          },
          {
            "name": "Dr Amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "4da13297-617c-485d-9d8e-12baa6e8c1b3",
            "sourceColumn": "Dr Amount",
            "summarizeBy": "sum"
          },
          {
            "name": "Cr Amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "c3c00f95-15d4-41e5-a2a7-b62d2471f78e",
            "sourceColumn": "Cr Amount",
            "summarizeBy": "sum"
          },
          {
            "name": "Net Balance",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "a0392fc0-e360-4332-837d-d4ba057aac1b",
            "sourceColumn": "Net Balance",
            "summarizeBy": "sum"
          },
          {
            "name": "Balance Type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "70eed98d-fcf9-40f8-bb4d-909cafbeedf1",
            "sourceColumn": "Balance Type",
            "summarizeBy": "none"
          },
          {
            "name": "Balance",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "0ce4aa56-dc41-4276-a920-338afd95c61c",
            "sourceColumn": "Balance",
            "summarizeBy": "sum"
          },
          {
            "name": "ACT ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "50fee24a-55d1-4050-836e-ba3660dbbc03",
            "sourceColumn": "ACT ID",
            "summarizeBy": "none"
          },
          {
            "name": "SA ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "356d64b6-2b77-46fe-86b8-3f009249c75c",
            "sourceColumn": "SA ID",
            "summarizeBy": "none"
          },
          {
            "name": "FS ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5f756c03-0114-41e9-ac1a-3ec6096c2b2a",
            "sourceColumn": "FS ID",
            "summarizeBy": "none"
          },
          {
            "name": "Account Categories",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c06c8a27-7982-4278-a959-1025d58e18d9",
            "sourceColumn": "Account Categories",
            "summarizeBy": "none"
          },
          {
            "name": "Sub Account",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2232874a-266b-4c25-b200-b337a6c05243",
            "sourceColumn": "Sub Account",
            "summarizeBy": "none"
          },
          {
            "name": "Financial Statements",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a576c49f-86aa-4b54-a3f8-19ab0570ebcd",
            "sourceColumn": "Financial Statements",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "b679f5d8-294b-4068-9227-8475264de49d",
        "partitions": [
          {
            "name": "uc?export=download&id=1dPCDeD6N8GAZnzQ3QbfP7T_jYD1jYh0G",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(Web.Contents(\"https://drive.google.com/uc?export=download&id=1dPCDeD6N8GAZnzQ3QbfP7T_jYD1jYh0G\"),[Delimiter=\",\", Columns=13, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Account ID\", type text}, {\"Account Name\", type text}, {\"Dr Amount\", type text}, {\"Cr Amount\", type text}, {\"Net Balance\", Int64.Type}, {\"Balance Type\", type text}, {\"Balance\", Int64.Type}, {\"ACT ID\", type text}, {\"SA ID\", type text}, {\"FS ID\", type text}, {\"Account Categories\", type text}, {\"Sub Account\", type text}, {\"Financial Statements\", type text}}),",
                "    #\"Replaced Value\" = Table.ReplaceValue(#\"Changed Type\",\"-\",\"0\",Replacer.ReplaceText,{\"Dr Amount\"}),",
                "    #\"Replaced Value1\" = Table.ReplaceValue(#\"Replaced Value\",\"-\",\"0\",Replacer.ReplaceText,{\"Cr Amount\"}),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Replaced Value1\",{{\"Cr Amount\", type number}, {\"Dr Amount\", type number}})",
                "in",
                "    #\"Changed Type1\""
              ],
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}